### ISSUE TITLE
device 清單優先讀取DB  再SCAN  加快載入速度

### ISSUE THREAD

**Issue by kyoyadmoon** [trunk-studio/hme-web-api#114]
新增 get API ＆前端串接

**Comment by kyoyadmoon** [comment]
scanDevice優先讀取db deviceList這部分我把scan跟讀取DB拆成兩個API
```
searchDevice
getCachedDeviceList
```
getCachedDeviceList 這個 action 會先去讀DB的device model
如果沒資料會去call searchDevice ，search完之後再return 

頁面載入時就先call getCachedDeviceList()
SCAN按鈕的 click event則是 call searchDevice()

這樣的流程可以嗎？

**Comment by smlsunxie** [comment]
getCachedDeviceList 這個 action 會先去讀DB的device model
如果沒資料會去call searchDevice ，search完之後再return
return 時在寫入資料庫
...

**Comment by kyoyadmoon** [comment]
這邊寫入我應該會寫在searchDevice裡面
