### ISSUE TITLE
色溫畫面修正

### ISSUE THREAD

**Issue by FuYaoDe** [trunk-studio/hme-web-api#257]
![screenshot 2016-02-04 15 58 13](https://cloud.githubusercontent.com/assets/6357215/12809207/1f55998c-cb58-11e5-9fda-77034ace6ae8.png)

**Comment by nanasigodo** [comment]
![2500-9000](https://cloud.githubusercontent.com/assets/15866311/12811029/c28e2d2e-cb64-11e5-9f55-8cad35feb0b2.png)
