### ISSUE TITLE
新增 service 更新 rtc 時間

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/hme-web-api#261]
參考下列進行 pi 設置

https://pragmaticmonk.wordpress.com/2014/03/15/using-rtc-pcf8563-on-raspberry-pi-running-raspbian-os/

流程上，先更新 ubuntu 系統時間，參考

https://www.garron.me/en/linux/set-time-date-timezone-ntp-linux-shell-gnome-command-line.html

更新時間以及 timezone

透過 `hwclock --hctosys or hwclock -w` 更新硬體  rtc

在透過 `hwclock -s` 將硬體的 rtc 更新 system time

最後再透過 `hwclock –r` 回傳設置結果

設置 timezone http://askubuntu.com/questions/3375/how-to-change-time-zone-settings-from-the-command-line
在 node js 使用 

https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

來執行整個更新指令

### master 系統時間更新

1. 更新 system time (若有連網的話會被 ntpdate 覆蓋)，此步驟需要在 server reboot 前完成

下面步驟將在 system reboot 後，在系統 startup 時進行
Run on startup 先用 rc.local 就好，下階段有需要再包成 service

2. 根據  hme.txt 設置 timezone
2. 透過 hwclock -w 寫入硬體時間

如此就處理完 master 的系統時間

### slave 系統時間更新

接著理論上 slave 註冊時，會需要確認 master 的存在，在註冊時順便透過 `ntpdate hmems0001.local` 進行第一次的 system 的更新。

爾後，透過 slave 重啟，或是訂一個時段透過 crontab 在執行一次 `ntpdate hmems0001.local` 跟 master sync

後續要還要串接，將硬體 rtc 寫入 device 所以需要 @weberber 再提供相關的 api，如此 server 還要再提供 sync device 的 api 以便之後呼叫

**Comment by lyhcode** [comment]
考慮 master ----> slave (1..*) 的 date/time update

**Comment by lyhcode** [comment]
另一種 multi node 的時間同步方法，就是直接搭配 NTP 的 subnet broadcast

/etc/ntp.conf 

```
# If you want to provide time to your local subnet, change the next line.
# (Again, the address is an example only.)
#broadcast 192.168.123.255

# If you want to listen to time broadcasts on your local subnet, de-comment the
# next lines.  Please do this only if you trust everybody on the network!
#disable auth
#broadcastclient
```

好處是會自動運作，
但這有一個麻煩的地方，
就是 broadcast 需要指定 subnet (e.g. 192.168.123.255)
每次換不同的 wifi subnet 都要跟著變。

**Comment by lyhcode** [comment]
從 slave 自動向 master 索取時間來更新的做法：

假設 master 為 `hmems0001`

1. `ntpdate hmems0001.local`

2. `htpdate hmems0001.local`

ntpdate 是走標準的 NTP protocol

htpdate 是走 HTTP protocol 透過 http request 拿回 http server response 時間

**Comment by smlsunxie** [comment]
先從 service 製作，之後會再加上 rest api，有了 service rest api 就不是問題了

看 @lyhcode 的說明目前應該還是先用我提供的做法對吧？

ntpdate 可以在 slave 註冊到 master 時，一併處理

搭配   http://technote.aven-network.com/20/%E4%BD%BF%E7%94%A8-ntp-%E6%95%88%E5%B0%8D%E6%99%82%E9%96%93

**Comment by lyhcode** [comment]
5 分鐘 sync 一次時間太頻繁，
應該只要兩種情況 sync：

1. slave 開機完成、連線後自動 sync，讓時間和 master 同步
2. 每天一次自動 sync 修正時間差

**Comment by lyhcode** [comment]
另外想到一個問題，目前的 setup 畫面，設定 timezone，這個 timezone 應該也要同步設定到所有 slave

```
/rest/slave/:slaveId/timezone/TIMEZONE
```

**Comment by smlsunxie** [comment]
這部分在做時間同步時就會一併處理，這樣看來應該要有兩個方向

1. 時間設定設置後，透過 api 進行更新
2. 一旦設置後，透過 cron job 進行之後的跟 master 進行時間同步

**Comment by lyhcode** [comment]
timezone 的設置可能會比較麻煩

因為格式是類似：

```
Asia/Taipei
```

跟一般 web 操作設定用的 +08:00 這需要做 mapping

如果要走比較簡單的方式

有可能是所有的 RPi Linux 系統都走 Universal Time

要顯示到網頁上的時候才根據 user 設定的 timezone 顯示成 Local Time

**Comment by smlsunxie** [comment]
全域性的 slave 更新 api 

/rest/master/syncAllSlaveUTC

透過上述的呼叫， for 每個 salve 呼叫

/rest/slave/:slaveId/timestamp/:TIMESTAMP/timezone/:TIMEZONE

**Comment by lyhcode** [comment]
```
/rest/slave/:slaveId/timezone/:TIMEZONE/timestamp/:TIMESTAMP
```

**Comment by smlsunxie** [comment]
1. ui timezone 改為用 GMT +- 8
2. 有一個指令透過 timezone 更新 master 的  datetime(透過 service 用 spec 測試)
. loadEnv.sh -c=hme.txt && npm test

3. slave 啟動的時候透過 https://github.com/trunk-studio/hme-web-api/issues/261#issuecomment-179874587 的指令跟 master 同步

4. slave 還需要有個 api 進行手動使用第 3 步驟
