### ISSUE TITLE
Test Case - 從 WiFi AP mode 切換至 Client mode 的 Avahi/Bounjour mDNS cache 問題

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/hme-web-api#302]
1. 假設 手機 連線到 RPi with AP mode
    網路是 192.168.255.x
    所以 `hmems0001.local` 對應到 192.168.255.249

2. 當 Setup 成功後，RPi 從 AP mode 變成 Client Mode
    網路是 192.168.100.x
    假如 `hmems0001.local` 對應到 192.168.100.174

這時候瀏覽器回不會仍然讀到 Cache 的 hmems0001.local => 192.168.255.249

**Comment by smlsunxie** [comment]
@FuYaoDe 測試一下，把有線網路拔除，然後進行 wifi setup 流程以及 reset 看看是否程序上對於 pi 的連接是否都正常

**Comment by smlsunxie** [comment]
確認正常，有調整 wlan0 之 port forwarding
