### ISSUE TITLE
參考 Google Chromecast 的 AP mode 配置

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/hme-web-api#303]
使用網段 192.168.255.x

預設的 RPi 裝置位址 192.168.255.249

考慮到 USB WiFi dongle 連線能力有限

只允許某一個 RANGE 數量的裝置連入

e.g. 只允許十個連入 192.168.255.201-210

**Comment by smlsunxie** [comment]
got 我在調整一下設置
