### ISSUE TITLE
修訂schedule頁面設定所屬分組之配置方式

### ISSUE THREAD

**Issue by weberber** [trunk-studio/hme-web-api#46]
![ui](https://cloud.githubusercontent.com/assets/16112909/12045767/20b45320-aee5-11e5-936c-7a1bee203d19.png)

**Comment by smlsunxie** [comment]
:+1:

**Comment by smlsunxie** [comment]
我看沒有問題，但有可能在第一頁只是顯示，點進去維護時才進行 group device 得選去
這個我現在還沒有定案，等功能串差不多
再來看要怎麼配置
